name: Deploy to DigitalOcean

on:
  push:
    branches: [ wedding-prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout кода
      - name: Checkout code (обязательно первым)
        uses: actions/checkout@v3

      # Шаг 2: Подготовьте окружение на CI, если в будущем будете что-то выполнять здесь
      - name: Set up Node.js locally
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Шаг 3: Отправка всего кода проекта на удаленный сервер
      - name: Deploy Full Project
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.WEDDING_DEPLOY_PRIVATE_KEY }}
          source: ./ # Исходные файлы проекта
          target: /root/calculator-buh-back # Цель на сервере

      # Шаг 4: SSH в сервер, установка зависимостей, сборка, запуск
      - name: SSH to server and build project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.WEDDING_DEPLOY_PRIVATE_KEY }}
          script: |
            cd /root/calculator-buh-back
            rm -rf node_modules
            npm install --production --force
            npm run build
            pm2 restart weddingback || pm2 start dist/index.js --name weddingback
            pm2 save
            sudo systemctl restart nginx