name: Deploy to DigitalOcean

on:
  push:
    branches: [ wedding-prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.WEDDING_DEPLOY_PRIVATE_KEY }}
          source: dist/ # Указана ваша директория сборки
          target: /root/calculator-buh-back # Указан путь до вашего проекта на сервере

      - name: SSH to server and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.WEDDING_DEPLOY_PRIVATE_KEY }}
          script: |
            cd /root/calculator-buh-back
            npm install --production
            pm2 restart weddingback
            sudo systemctl restart nginx